# Generated by Django 5.2.17 on 2026-09-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_image'),
        ('store', '0004_product_backlit_keyboard_product_battery_cell_and_more'),
    ]

    operations = [
    ]
