# Generated by Django 5.2.17 on 2026-10-03 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_merge_20260928_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
