# Generated by Django 5.2.17 on 2026-10-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_seller',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
